// Generated by https://quicktype.io

export interface SongList {
  id: number;
  type: number;
  name: string;
  copywriter: Copywriter;
  picUrl: string;
  canDislike: boolean;
  trackNumberUpdateTime: number;
  playCount: number;
  trackCount: number;
  highQuality: boolean;
  alg: Alg;
}

export enum Alg {
  CityLevelUnknow = "cityLevel_unknow",
  Featured = "featured",
}

export enum Copywriter {
  热门推荐 = "热门推荐",
  编辑推荐有爱的人天涯浪迹 = "编辑推荐：有爱的人，天涯浪迹",
  编辑推荐遇到合拍的人要比遇到让你动心的人要难得 = "编辑推荐：遇到合拍的人要比遇到让你动心的人要难得",
}
