// Generated by https://quicktype.io

export interface DjprogramResult {
  code: number;
  category: number;
  result: Djprogram[];
}

export interface Djprogram {
  id: number;
  type: number;
  name: string;
  copywriter: string;
  picUrl: string;
  canDislike: boolean;
  trackNumberUpdateTime: null;
  program: Program;
  alg: string;
}

export interface Program {
  mainSong: MainSong;
  songs: null;
  dj: Dj;
  blurCoverUrl: string;
  radio: Radio;
  subscribedCount: number;
  reward: boolean;
  mainTrackId: number;
  serialNum: number;
  listenerCount: number;
  name: string;
  id: number;
  createTime: number;
  description: string;
  userId: number;
  coverUrl: string;
  commentThreadId: string;
  channels: string[];
  titbits: null;
  titbitImages: null;
  pubStatus: number;
  trackCount: number;
  bdAuditStatus: number;
  programFeeType: number;
  buyed: boolean;
  programDesc: null;
  h5Links: any[];
  coverId: number;
  adjustedPlayCount: number;
  canReward: boolean;
  auditStatus: number;
  publish: boolean;
  duration: number;
  isPublish: boolean;
}

export interface Dj {
  defaultAvatar: boolean;
  province: number;
  authStatus: number;
  followed: boolean;
  avatarUrl: string;
  accountStatus: number;
  gender: number;
  city: number;
  birthday: number;
  userId: number;
  userType: number;
  nickname: string;
  signature: string;
  description: string;
  detailDescription: string;
  avatarImgId: number;
  backgroundImgId: number;
  backgroundUrl: string;
  authority: number;
  mutual: boolean;
  expertTags: string[] | null;
  experts: Experts | null;
  djStatus: number;
  vipType: number;
  remarkName: null;
  authenticationTypes: number;
  avatarDetail: null;
  avatarImgIdStr: string;
  backgroundImgIdStr: string;
  anchor: boolean;
  brand: string;
  avatarImgId_str?: string;
}

export interface Experts {
  "1": string;
}

export interface MainSong {
  name: string;
  id: number;
  position: number;
  alias: any[];
  status: number;
  fee: number;
  copyrightId: number;
  disc: string;
  no: number;
  artists: Artist[];
  album: Album;
  starred: boolean;
  popularity: number;
  score: number;
  starredNum: number;
  duration: number;
  playedNum: number;
  dayPlays: number;
  hearTime: number;
  ringtone: string;
  crbt: null;
  audition: null;
  copyFrom: string;
  commentThreadId: string;
  rtUrl: null;
  ftype: number;
  rtUrls: any[];
  copyright: number;
  transName: null;
  sign: null;
  mark: number;
  originCoverType: number;
  originSongSimpleData: null;
  single: number;
  noCopyrightRcmd: null;
  mp3Url: null;
  mvid: number;
  bMusic: Music;
  rtype: number;
  rurl: null;
  hMusic: Music | null;
  mMusic: null;
  lMusic: Music;
}

export interface Album {
  name: string;
  id: number;
  type: null;
  size: number;
  picId: number;
  blurPicUrl: null;
  companyId: number;
  pic: number;
  picUrl: string;
  publishTime: number;
  description: string;
  tags: string;
  company: null;
  briefDesc: string;
  artist: Artist;
  songs: any[];
  alias: any[];
  status: number;
  copyrightId: number;
  commentThreadId: string;
  artists: Artist[];
  subType: null;
  transName: null;
  onSale: boolean;
  mark: number;
}

export interface Artist {
  name: string;
  id: number;
  picId: number;
  img1v1Id: number;
  briefDesc: string;
  picUrl: string;
  img1v1Url: string;
  albumSize: number;
  alias: any[];
  trans: string;
  musicSize: number;
  topicPerson: number;
}

export interface Music {
  name: null;
  id: number;
  size: number;
  extension: Extension;
  sr: number;
  dfsId: number;
  bitrate: number;
  playTime: number;
  volumeDelta: number;
}

export enum Extension {
  Mp3 = "mp3",
}

export interface Radio {
  id: number;
  dj: null;
  name: string;
  picUrl: string;
  desc: string;
  subCount: number;
  programCount: number;
  createTime: number;
  categoryId: number;
  category: string;
  radioFeeType: number;
  feeScope: number;
  buyed: boolean;
  videos: null;
  finished: boolean;
  underShelf: boolean;
  purchaseCount: number;
  price: number;
  originalPrice: number;
  discountPrice: null;
  lastProgramCreateTime: number;
  lastProgramName: null;
  lastProgramId: number;
  picId: number;
  rcmdText: null | string;
  hightQuality: boolean;
  whiteList: boolean;
  composeVideo: boolean;
}
